### ISSUE TITLE
[Feature request] Save evaluation as Draft

### ISSUE THREAD

**Issue by gndelia** [CommonJobs/CommonJobs#521]
Not sure if the project is still alive (?) 

I think the Auto-Evaluation is missing a "Save as draft" button. I'm doing my self-evaluation, and I've completed a bunch of the fields, but there are others that I'm not sure how to complete, and I wish to continue tomorrow to give some time to think about the comments. However, in order to not to lose the comments I've made, I need to save them in a word (?) as there is no save without submit button.

![image](https://user-images.githubusercontent.com/352474/95390616-0e3a8980-08cc-11eb-9bce-04eea3198a93.png)

Therefore, this ticket is to add the "save as draft" functionality. I think it would basically save the self-evaluation without actually submitting it, and then once submitted there's no way back

Given that the project states below that we could just do the PR, _I might_ be able to do it sometime (but I don't know who will merge or who is it in charge of it), so this ticket is also to verify that 👀 

edit: Option b: save in local storage and don't use draft at all: it will "just work", unless we expect to see the content in other devices for the same user 😋

**Comment by andresmoschini** [comment]
Hello @gndelia, thanks for the detailed information.

> Not sure if the project is still alive (?)

No, it is not so much active.

> I think the Auto-Evaluation is missing a "Save as draft" button. I'm doing my self-evaluation, and I've completed a bunch of the fields, but there are others that I'm not sure how to complete, and I wish to continue tomorrow to give some time to think about the comments. However, in order to not to lose the comments I've made, I need to save them in a word (?) as there is no save without submit button.

I think that you can save a draft using the button in the header:

![image](https://user-images.githubusercontent.com/1157864/95459086-82674280-0949-11eb-8a35-11e9f6a4460c.png)

I am not sure who is the IT responsible for this cicle. But let me know if you have more doubts, we can also chat in slack.

Regards.

**Comment by gndelia** [comment]
Thanks! I can't believe I did not see it, it was completely out of my sight. I guess I did not expect it to be in the header and my brain filtered it out.

You can close this, thanks for the response!

**Comment by andresmoschini** [comment]
> Thanks! I can't believe I did not see it, it was completely out of my sight. I guess I did not expect it to be in the header and my brain filtered it out.

Hehe, usability is not the strong point of this application :P
